### ISSUE TITLE
Taller de Programación II no es una equivalencia de Ing. de Software II.

### ISSUE THREAD

**Issue by Ezequiel-Schejtman** [ManuelBilbao/FIUBA-Transicion#9]
Por lo que estuve leyendo en el [plan enviado por mail desde el Depto. de Computación](https://docs.google.com/document/d/1mfRbld_W5QDnMSQP5Pwa8rqKPWK3xM4I/edit), Taller de Programación II **no otorga** Ing. de Software II. Entiendo debería debería contar como 4 créditos de electivas.

**Comment by ManuelBilbao** [comment]
Buenas, por lo que vi hay varias equivalencias que no aparecen en el documento. No estoy 100% seguro pero creo que es por una cuestión de que son correlativas _temporales_. Si tenés alguna respuesta _oficial_ de eso, avisame y lo cambio
